# Generated by Django 4.1.1 on 2022-10-11 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('genero', models.IntegerField(choices=[[1, 'Masculino'], [2, 'Femenino'], [3, 'No binario']])),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('generos_preferencia', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Accion'), (2, 'Aventura'), (3, 'Terror'), (4, 'Ciencia Ficcion'), (5, 'Romance'), (6, 'Humor'), (7, 'Poesia'), (8, 'Novela')], max_length=3)),
                ('direccion_correspondencia', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
