# Generated by Django 4.1.1 on 2022-10-11 05:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='generos_preferencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Accion'), (2, 'Aventura'), (3, 'Terror'), (4, 'Ciencia Ficcion'), (5, 'Romance'), (6, 'Humor'), (7, 'Poesia'), (8, 'Novela')], max_length=100),
        ),
    ]
