# Generated by Django 4.1.1 on 2022-10-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfilusuario_generos_preferencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Editorial',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='editorial',
        ),
        migrations.AddField(
            model_name='producto',
            name='autor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Accion'), (2, 'Aventura'), (3, 'Terror'), (4, 'Ciencia Ficcion'), (5, 'Romance'), (6, 'Humor'), (7, 'Poesia'), (8, 'Novela')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='issn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='num_paginas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
