# Generated by Django 4.1.1 on 2022-10-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_marca_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='issn',
            field=models.IntegerField(unique=True),
        ),
    ]
