# Generated by Django 4.1.1 on 2022-10-17 06:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_producto_issn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='lugar_nacimiento',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
