# Generated by Django 4.1.1 on 2022-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_perfilusuario_lugar_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='DNI',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'No binario')]),
        ),
    ]
