# Generated by Django 4.1.1 on 2022-10-31 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_perfilusuario_dni_alter_perfilusuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='DNI',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
