# Generated by Django 4.1.1 on 2022-10-31 22:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_perfilusuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion_correspondencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='lugar_nacimiento',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
