# Generated by Django 4.1.1 on 2022-10-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_perfilusuario_direccion_correspondencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'No binario')]),
        ),
    ]
