# Generated by Django 4.1.1 on 2022-10-31 23:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_perfilusuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion_correspondencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'No binario')]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='lugar_nacimiento',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
