# Generated by Django 4.1.1 on 2022-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_perfilusuario_direccion_correspondencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='fotoperfil'),
        ),
    ]
