# Generated by Django 4.1.1 on 2022-11-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='lugar_nacimiento',
        ),
    ]
