# Generated by Django 4.1.1 on 2022-11-03 17:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('app', '0015_remove_perfilusuario_lugar_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
    ]
