# Generated by Django 4.1.1 on 2022-11-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_perfilusuario_ciudad_perfilusuario_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
