# Generated by Django 4.1.1 on 2022-11-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='creado_en',
            new_name='created_at',
        ),
    ]
