# Generated by Django 4.1.1 on 2022-11-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_creado_en_carrito_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto',
            new_name='product',
        ),
    ]
