# Generated by Django 4.1.1 on 2022-11-11 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_existencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.IntegerField()),
                ('nombre_tarjeta', models.CharField(max_length=50)),
                ('mes_exp', models.IntegerField()),
                ('year_exp', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
