# Generated by Django 4.1.1 on 2022-11-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='nombre_tarjeta',
        ),
    ]
