# Generated by Django 4.1.1 on 2022-11-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_tarjeta_nombre_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='nombre_propietario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
