# Generated by Django 4.1.1 on 2022-11-15 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_noticia_forum_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True)),
                ('lname', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('celular', models.CharField(max_length=150, null=True)),
                ('direccion', models.TextField(null=True)),
                ('pais', models.CharField(max_length=150, null=True)),
                ('ciudad', models.CharField(max_length=150, null=True)),
                ('dni', models.CharField(max_length=150, null=True)),
                ('fecha_nacimiento', models.CharField(max_length=150, null=True)),
                ('precio_total', models.FloatField(null=True)),
                ('forma_pago', models.CharField(max_length=150, null=True)),
                ('forma_pago_id', models.CharField(max_length=150, null=True)),
                ('estatus', models.CharField(choices=[('En envio', 'En envio'), ('Completado', 'Completado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=150)),
                ('mensaje', models.TextField(null=True)),
                ('seguimiento_num', models.CharField(max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
