# Generated by Django 4.1.1 on 2022-11-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_orden_ordenitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='topic',
            new_name='tema',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
