# Generated by Django 4.1.1 on 2022-11-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_description_forum_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('En envio', 'En envio'), ('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=150),
        ),
    ]
