# Generated by Django 4.1.1 on 2022-11-17 19:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_orden_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En envio', 'En envio'), ('Completado', 'Completado')], default='Pendiente', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion_correspondencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoperfil'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='generos_preferencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Accion'), (2, 'Aventura'), (3, 'Terror'), (4, 'Ciencia Ficcion'), (5, 'Romance'), (6, 'Humor'), (7, 'Poesia'), (8, 'Novela')], max_length=100, null=True),
        ),
    ]
