# Generated by Django 4.1.1 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_orden_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('En envio', 'En envio'), ('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=150),
        ),
    ]
