# Generated by Django 4.1.1 on 2022-11-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_reserva_cantidad_producto_alter_orden_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='producto',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('En envio', 'En envio'), ('Completado', 'Completado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=150),
        ),
    ]
