# Generated by Django 4.1.1 on 2022-11-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_orden_estatus_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En envio', 'En envio'), ('Cancelada', 'Cancelada'), ('Completado', 'Completado')], default='Pendiente', max_length=150),
        ),
    ]
