# Generated by Django 4.1.1 on 2022-11-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_orden_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Cancelada', 'Cancelada'), ('En envio', 'En envio'), ('Devuelta', 'Devuelta')], default='Pendiente', max_length=150),
        ),
    ]
