from django.urls import path
from .views import *
from app.controller import cart, checkout, orden

urlpatterns = [
    path('',            home,       name="home"),
    path('contacto/',   contacto,   name="contacto"),
    path('galeria/',    galeria,    name="galeria"),
    path('agregar-producto/',    agregar_producto,    name="agregar_producto"),
    path('listar-productos/',    listar_productos,    name="listar_productos"),
    path('modificar-producto/<id>/',    modificar_producto,    name="modificar_producto"),
    path('eliminar-producto/<id>/',    eliminar_producto,    name="eliminar_producto"),
    path('detalle-producto/<int:pk>/',    DetalleLibro.as_view(),    name="detalle_libro"),
    path('agregar-tienda/',    agregar_tienda,    name="agregar_tienda"),
    path('listar-tiendas/',    listar_tiendas,    name="listar_tiendas"),
    path('modificar-tienda/<id>/',    modificar_tienda,    name="modificar_tienda"),
    path('recoger-tienda/',    recoger_tienda,    name="recoger_tienda"),
    path('eliminar-tienda/<id>/',    eliminar_tienda,    name="eliminar_tienda"),
    path('agregar-existencias/<id>/<id2>/',    agregar_existencias,    name="agregar_existencias"),
    path('aumentar-existencias/<id>/<id2>/<id3>',    aumentar_existencias_t,    name="aumentar_existencias"),
    path('eliminar-existencias/<id>/<id2>/<id3>',    eliminar_existencias_t,    name="eliminar_existencias"),
    path('listar-existencias/<id>/',    listar_existencias,    name="listar_existencias"),
    path('escoger-existencia/<id>/',    escoger_existencias,    name="escoger_existencia"),
    path('registro/',    registro,    name="registro"),
    path('ver-perfil/',    ver_perfil,    name="ver_perfil"),
    path('modificar-perfil/',    modificar_perfil,    name="modificar_perfil"),
    path('eliminar-perfil/<int:pk>/',    eliminar_perfil.as_view(),    name="eliminar_perfil"),
    path('cambiar-contraseña',    cambiar_contrasenia.as_view(),    name="cambiar_contraseña"),
    path('add-to-cart', cart.addtocart, name="addtocart"),
    path('cart', cart.viewcart, name="cart"),
    path('update-cart', cart.updatecart, name="updatecart"),
    path('delete-cart-item', cart.deletecartitem, name="deletecartitem"),
    path('checkout', checkout.index, name="checkout"),
    path('checkout-tienda/<id>/', checkout_tienda, name="checkout_tienda"),
    path('checkout-tienda-orden/<id>/', checkout_tienda_orden, name="checkout_tienda_orden"),
    path('placerorder', checkout.placeorder, name="placeorder"),
    path('listar-tarjetas/',    listar_tarjetas,    name="listar_tarjetas"),
    path('agregar-saldo/<id>',    agregar_saldo,    name="agregar_saldo"),
    path('eliminar-tarjeta/<id>',    eliminar_tarjeta,    name="eliminar_tarjeta"),
    path('tarjeta/',    tarjeta,    name="tarjeta"),
    path('forum/', forums, name="forum"),
    path('addInForum/',addInForum,name='addInForum'),
    path('addInDiscussion/<id>/',addInDiscussion,name='addInDiscussion'),
    path('mapa/',    mapa,    name="mapa"),
    path('listar-noticias/', listar_noticias, name="listar_noticias"),
    path('eliminar-noticia/<id>/', eliminar_noticia, name="eliminar_noticia"),
    path('mis-ordenes/', orden.index , name="ordenes"),
    path('ver-orden/<str:t_no>/', orden.verorden , name="verorden"),
    path('cancelar-orden/<str:t_no>/', orden.cancelar_orden , name="cancelar_orden"),
    path('realizar-devolucion/<str:t_no>/', orden.realizar_devolucion , name="realizar_devolucion"),
    path('add-to-cart-reserva', cart.addtocartReserva, name="addtocartreserva"),

    path('reservar-libro', cart.RegistrarReserva , name="reservar_libro"),
    path('ver-reserva', cart.viewreserva , name="ver_reserva"),
    path('delete-reserva-item', cart.deletereservaitem, name="deletereservaitem"),

]